// src/quests.ts
export type QuestInfo = { title: string; desc: string };

export const QUESTS: Record<number, QuestInfo> = {
  1:{title:"Pull No Punches",desc:"Deal 10000 Damage"},
  2:{title:"Chemical Warfare",desc:"Deal 2000 Damage Through Status Effects"},
  3:{title:"Minor Handicap",desc:"Win 2 Battles with Bjorn without using Roar"},
  4:{title:"Minor Handicap",desc:"Win 2 Battles with Skaerrot without using Homing Carrot"},
  5:{title:"Minor Handicap",desc:"Win 2 Battles with Madhattr without using Teleport"},
  6:{title:"Minor Handicap",desc:"Win 2 Battles with Hushroom without using Spore Bomb"},
  7:{title:"Minor Handicap",desc:"Win 2 Battles with Bigghaer without using Spirit Shroud"},
  8:{title:"Minor Handicap",desc:"Win 2 Battles with Igby without using Flame Frenzy"},
  9:{title:"Minor Handicap",desc:"Win 2 Battles with Flindorr without using Poisonous Pollen"},
  10:{title:"Minor Handicap",desc:"Win 2 Battles with Klautjásar without using Stormy Puff"},
  11:{title:"Minor Handicap",desc:"Win 2 Battles with Orni without using Martial Gusto"},
  12:{title:"Marksman",desc:"Deal Damage from at least 5 tiles away 10 times."},
  13:{title:"Rune Hunter",desc:"Defeat all Rune types"},
  14:{title:"Grand Champ",desc:"Win 3 battles without any of your Veras being defeated."},
  15:{title:"Diverse Duels",desc:"Defeat 4 different Vera species"},
  16:{title:"Its a Knockout!",desc:"Deal the final blow on a Vera with Vera collision"},
  17:{title:"Close Quarters Combat",desc:"Win 9 Vera collisions"},
  18:{title:"Anger Management",desc:"Defeat 2 Enraged Vera"},
  19:{title:"Going Pro",desc:"Win 3 ranked battles"},
  20:{title:"Self Care",desc:"Heal 400 health"},
  21:{title:"Hot Streak",desc:"Win 3 battles in a row"},
  22:{title:"Challenge Run",desc:"Win 5 battle(s) without using any potions"},
  23:{title:"Healthy Upbringing",desc:"Level up a Vera 2 times"},
  24:{title:"Crushing Strikes",desc:"Perform 10 critical hits"},
  25:{title:"One Trick Pony",desc:"Win 3 battles using Hushroom"},
  26:{title:"One Trick Pony",desc:"Win 3 battles using Madhattr"},
  27:{title:"One Trick Pony",desc:"Win 3 battles using Skaerrot"},
  28:{title:"One Trick Pony",desc:"Win 3 battles using Bjorn"},
  29:{title:"One Trick Pony",desc:"Win 3 battles using Bigghaer"},
  30:{title:"One Trick Pony",desc:"Win 3 battles using Igby"},
  31:{title:"One Trick Pony",desc:"Win 3 battles using Flindorr"},
  32:{title:"One Trick Pony",desc:"Win 3 battles using Klautjásar"},
  33:{title:"One Trick Pony",desc:"Win 3 battles using Orni"},
  34:{title:"Fire With Fire",desc:"Defeat an opponent's Vera using the same Vera."},
  35:{title:"Picky Hitter",desc:"Deal 8000 Physical Damage"},
  36:{title:"Picky Hitter",desc:"Deal 8000 Magical Damage"},
  37:{title:"Picky Hitter",desc:"Deal 8000 Primal Damage"},
  38:{title:"Rune Acquisition",desc:"Tame 2 Veras of Hail Rune Type"},
  39:{title:"Rune Acquisition",desc:"Tame 2 Veras of Sun Rune Type"},
  40:{title:"Rune Acquisition",desc:"Tame 2 Veras of Nature Rune Type"},
  41:{title:"Going All Out",desc:"Deal More than 300 Damage In One Turn"},
  42:{title:"Hitting Hard",desc:"Deal More than 1300 Damage In One Battle"},
  43:{title:"Unbreakable",desc:"Take 1000 Damage"},
  44:{title:"Vera Control",desc:"Defeat 4 Bjorn"},
  45:{title:"Vera Control",desc:"Defeat 4 Hushroom"},
  46:{title:"Vera Control",desc:"Defeat 4 Madhattr"},
  47:{title:"Vera Control",desc:"Defeat 3 Bigghaer"},
  48:{title:"Vera Control",desc:"Defeat 3 Skaerrot"},
  49:{title:"Vera Control",desc:"Defeat 3 Igby"},
  50:{title:"Vera Control",desc:"Defeat 4 Flindorr"},
  51:{title:"Vera Control",desc:"Defeat 3 Klautjásar"},
  52:{title:"Vera Control: Orni",desc:"Defeat 4 Orni"},
  53:{title:"Vera Control",desc:"Defeat any 8 Veras"},
  54:{title:"Charging Cycle",desc:"Spend 700 Charge"},
  55:{title:"Bottoms Up",desc:"Use 5 Potions"},
  56:{title:"Marathon Runner",desc:"Move Your Vera 20 Times"},
  57:{title:"Vera Wrangler",desc:"Tame a Bjorn"},
  58:{title:"Vera Wrangler",desc:"Tame a Hushroom"},
  59:{title:"Vera Wrangler",desc:"Tame a Skaerrot"},
  60:{title:"Vera Wrangler",desc:"Tame a Madhattr"},
  61:{title:"Vera Wrangler",desc:"Tame a Klautjasar"},
  62:{title:"Vera Wrangler",desc:"Tame a Bigghaer"},
  63:{title:"Vera Wrangler",desc:"Tame an Igby"},
  64:{title:"Vera Wrangler",desc:"Tame a Flindorr"},
  65:{title:"Vera Wrangler",desc:"Tame an Orni"},
  66:{title:"Vera Shelter",desc:"Tame 3 Veras"},
  67:{title:"All Work and No Play",desc:"Deposit or Withdraw 3 Vera at the Daycare"},
  68:{title:"Spendthrift",desc:"Buy Or Sell 3 Items"},
  69:{title:"Fighter",desc:"Finish 5 PvP Battles"},
};